core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words.urls')),
    path('', include('accounts.urls')),
    path('', include('leitner.urls')),
]


if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leitner/urls.py
from django.urls import path
from .views import *




app_name = "leitner"

urlpatterns = [
    path('test/', test,name="test"),
    path('addLword/<int:id>/', addLword,name="addLword"),
    path('ReviewLeitner/', ReviewLeitner,name="ReviewLeitner"),
    path('WordLearned/<int:id>/',WordLearned,name="WordLearned"),
    path('WordUnLearned/<int:id>/',WordUnLearned,name="WordUnLearned"),
]

words/urls.py
from django.urls import path
from .views import *




app_name = "words"

urlpatterns = [
    path('', panel,name="panel"),
    path('addWord/<int:pk>/', addWord,name="addWord"),
    path('addGroup/', addGroup,name="addGroup"),
    path('<int:pk>/', GpWords,name="home"),
    path('YourGp/', YourGp,name="YourGp"),
    # path('GpWords/<int:pk>/', GpWords,name="GpWords"),
    path('changeLearnCondition/<int:pk>', changeLearnCondition,name="changeLearnCondition"),

]

words/models.py
from django.db import models
from django.utils import timezone
from core.settings import AUTH_USER_MODEL as User

class group(models.Model):
    title = models.CharField(max_length=30)
    img = models.ImageField(null=True, blank=True)
    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name="groups")


    def __str__(self):
        return self.title

    def getId(self):
        return self.id


class word(models.Model):
    text = models.CharField(max_length=30)
    meaning = models.CharField(max_length=30)
    id = models.IntegerField(primary_key=True)
    gp = models.ForeignKey(group, on_delete=models.CASCADE,related_name="words")
    # cycle = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.text

    # def learn(self):
    #     if self.cycle > timezone.now():
    #         return False
    #     else:
    #         return True

    # def learned(self):
    #     self.cycle = timezone.now


    # learn.boolean = True

words/forms.py
from django import forms
from .models import *

class GpForm(forms.ModelForm):
    class Meta:
        model = group
        fields = ['title', 'img']


class WordForm(forms.ModelForm):
    class Meta:
        model = word
        fields = ['text', 'meaning']

words/views.py
from django.shortcuts import render
from .models import *
from leitner.models import *
import random
from .forms import *
from django.shortcuts import redirect



def home1(request):
    return render(request,'words/home.html')

#-----------------------------------------------------------------
def YourGp(request):
    gps = request.user.groups.all()
    print(gps)
    return render(request,'words/yourGp/YourGp.html',{'groups':gps})

#-----------------------------------------------------------------
def home(request,pk=0):
    max = word.objects.all().count()
    learned = word.objects.filter(learn=False).count()

    QueryWord = word.objects.get(id = 1)


    while((QueryWord.learn != False) and (learned!=1)):
        pk2 = random.randrange(1,max)
        QueryWord = word.objects.get(id = pk2)



    if(learned==1):
        QueryWord = word(text = "END!",meaning="cool!",id=1000)


    return render(request,'words/home.html',{'word':QueryWord})

#-----------------------------------------------------------------
def panel(request):
    groups = group.objects.all().order_by("-id")
    return render(request,'words/panel.html',{'groups':groups})
#-----------------------------------------------------------------
def addGroup(request):
    if request.method == 'POST':
        form = GpForm(request.POST, request.FILES)

        if form.is_valid():
            newgp = group(title = form.cleaned_data['title'],img = form.cleaned_data['img'],author=request.user).save()
            gp = group.objects.get(title=form.cleaned_data['title'])
            return redirect('words:addWord',gp.id)
    else:
        form = GpForm()
    return render(request,'words/addgp/name-pic.html',{'form':form})
#-----------------------------------------------------------------
def addWord(request,pk):
    if request.method == 'POST':
        form = WordForm(request.POST, request.FILES)

        if form.is_valid():
            newWord = word(text = form.cleaned_data['text'],meaning = form.cleaned_data['meaning'])
            gp = group.objects.get(id=pk)
            newWord.gp = gp
            newWord.save()
            return redirect('words:addWord',gp.id)
    else:
        form = WordForm()
    return render(request,'words/addgp/addWord.html',{'form':form})
#-----------------------------------------------------------------
def GpWords(request,pk):
    gp = group.objects.get(id = pk)
    wordsGP = gp.words.all()

    items = list(wordsGP)
    amount = 0

    for w in wordsGP:
        if(request.user.leitner.search(w)):
            pass
        else:
            amount+=1


    QueryWord = random.choice(items)

    while (request.user.leitner.search(QueryWord)) and (amount!=0):
        QueryWord = random.choice(items)



    if(amount==0):
        QueryWord = word(text = "END!",meaning="cool!",id=1000,gp=gp)

    return render(request,'words/group.html',{'word':QueryWord,'gp':gp})
#-----------------------------------------------------------------
def changeLearnCondition(request,pk):
    QueryWord = word.objects.get(id=pk)
    lt = request.user.leitner
    if not (lt.search(QueryWord)):
        lw = Lword(leitner=lt,words=QueryWord).save()
    lt.save()

    return GpWords(request,QueryWord.gp.id)
#-----------------------------------------------------------------

words/templates/words/panel-elements/apps.html
<div class="content-section">
 <div class="content-section-title">Start Fast !!!</div>
 <div class="apps-card">



  <div class="app-card">
   <span>
    <svg viewBox="0 0 512 512" fill="currentColor">
      <path d="M255.721 347.484L90.22 266.751v106.57l165.51 73.503 165.509-73.503V266.742z" />
      <path d="M511.441 189.361L255.721 64.617 0 189.361l255.721 124.744 195.522-95.378v111.032h30V204.092z" />
    </svg>
    Start Creating group
   </span>
   <div class="app-card__subtext">Edit, create and share with others</div>
   <div class="app-card-buttons">
    <button class="content-button status-button">Start</button>
    <!-- <div class="menu"></div> -->
   </div>
  </div>




  <div class="app-card">
   <span>
    <svg viewBox="0 0 512 512" fill="currentColor">
     <path d="M0 331v112.295a14.996 14.996 0 007.559 13.023L106 512V391L0 331zM136 391v121l105-60V331zM271 331v121l105 60V391zM406 391v121l98.441-55.682A14.995 14.995 0 00512 443.296V331l-106 60zM391 241l-115.754 57.876L391 365.026l116.754-66.15zM262.709 1.583a15.006 15.006 0 00-13.418 0L140.246 57.876 256 124.026l115.754-66.151L262.709 1.583zM136 90v124.955l105 52.5V150zM121 241L4.246 298.876 121 365.026l115.754-66.15zM271 150v117.455l105-52.5V90z" />
    </svg>
    Review Your Lietner Now!!
   </span>
   <div class="app-card__subtext">Test & learn your words group and give feedback to them for improve learning</div>
   <div class="app-card-buttons">
    <button class="content-button status-button"><a href="{% url 'leitner:ReviewLeitner' %}"style="text-decoration:none;Color:white">Review</a></button>
   </div>
  </div>



  <div class="app-card">
   <span>
    <svg viewBox="0 0 512 512" fill="currentColor">
      <path d="M352 0H64C28.704 0 0 28.704 0 64v320a16.02 16.02 0 009.216 14.496A16.232 16.232 0 0016 400c3.68 0 7.328-1.248 10.24-3.712L117.792 320H352c35.296 0 64-28.704 64-64V64c0-35.296-28.704-64-64-64z" />
      <path d="M464 128h-16v128c0 52.928-43.072 96-96 96H129.376L128 353.152V400c0 26.464 21.536 48 48 48h234.368l75.616 60.512A16.158 16.158 0 00496 512c2.336 0 4.704-.544 6.944-1.6A15.968 15.968 0 00512 496V176c0-26.464-21.536-48-48-48z" />
    </svg>
    Your Groups
   </span>
   <div class="app-card__subtext">Add New word to your groups</div>
   <div class="app-card-buttons">
    <button class="content-button status-button"><a href="{% url 'words:YourGp' %}"style="text-decoration:none;Color:white">Group List</a></button>
   </div>
  </div>
 </div>
</div>

words/templates/words/panel-elements/cover.html
<div class="content-wrapper-header">
 <div class="content-wrapper-context">
  <h2 >
   <!-- <svg viewBox="0 0 512 512">
    <path d="M467 0H45C20.099 0 0 20.099 0 45v422c0 24.901 20.099 45 45 45h422c24.901 0 45-20.099 45-45V45c0-24.901-20.099-45-45-45z" fill="#d6355b" data-original="#ff468c" />
    <path xmlns="http://www.w3.org/2000/svg" d="M512 45v422c0 24.901-20.099 45-45 45H256V0h211c24.901 0 45 20.099 45 45z" fill="#d6355b" data-original="#d72878" />
    <path xmlns="http://www.w3.org/2000/svg" d="M467 30H45c-8.401 0-15 6.599-15 15v422c0 8.401 6.599 15 15 15h422c8.401 0 15-6.599 15-15V45c0-8.401-6.599-15-15-15z" fill="#2e000a" data-original="#700029" />
    <path xmlns="http://www.w3.org/2000/svg" d="M482 45v422c0 8.401-6.599 15-15 15H256V30h211c8.401 0 15 6.599 15 15z" fill="#2e000a" data-original="#4d0e06" />
    <path xmlns="http://www.w3.org/2000/svg" d="M181 391c-41.353 0-75-33.647-75-75 0-8.291 6.709-15 15-15s15 6.709 15 15c0 24.814 20.186 45 45 45s45-20.186 45-45-20.186-45-45-45c-41.353 0-75-33.647-75-75s33.647-75 75-75 75 33.647 75 75c0 8.291-6.709 15-15 15s-15-6.709-15-15c0-24.814-20.186-45-45-45s-45 20.186-45 45 20.186 45 45 45c41.353 0 75 33.647 75 75s-33.647 75-75 75z" fill="#d6355b" data-original="#ff468c" />
    <path xmlns="http://www.w3.org/2000/svg" d="M391 361h-30c-8.276 0-15-6.724-15-15V211h45c8.291 0 15-6.709 15-15s-6.709-15-15-15h-45v-45c0-8.291-6.709-15-15-15s-15 6.709-15 15v45h-15c-8.291 0-15 6.709-15 15s6.709 15 15 15h15v135c0 24.814 20.186 45 45 45h30c8.291 0 15-6.709 15-15s-6.709-15-15-15z" fill="#d6355b" data-original="#d72878" />
   </svg> -->
   WORDS
  </h2>
  <div class="content-text">Just start your path learning and enjoy that</div>
  <button class="content-button"><a href="{% url 'words:addGroup' %}"style="text-decoration:none;Color:white">Create A Group of WORDS</a></button>
 </div>
 <img class="content-wrapper-img" src="https://assets.codepen.io/3364143/glass.png" alt="">
</div>

words/templates/words/panel-elements/installed.html
{% load static %}

<div class="content-section">
 <div class="content-section-title">Group of Words</div>
 <ul>
  {% for gp in groups %}

  <li class="adobe-product">
   <div class="products">
     <img class="list-img" src="{{gp.img}}" alt="">
    <p class="list-txt">{{gp}}</p>
   </div>
   <span class="status">
    <span class="status-circle green"></span>
    Updated</span>
   <div class="button-wrapper">
    <button class="content-button status-button open" ><a href="{% url 'words:home' gp.id %}" style="text-decoration:none;Color:white">Open</a></button>
   </div>
  </li>



  {% endfor %}

 </ul>
</div>