core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words.urls')),
    path('', include('accounts.urls')),
    path('', include('leitner.urls')),
]


if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

leitner/urls.py
from django.urls import path
from .views import *




app_name = "leitner"

urlpatterns = [
    path('test/', test,name="test"),
    path('addLword/<int:id>/', addLword,name="addLword"),
    path('ReviewLeitner/', ReviewLeitner,name="ReviewLeitner"),
    path('WordLearned/<int:id>/',WordLearned,name="WordLearned"),
    path('WordUnLearned/<int:id>/',WordUnLearned,name="WordUnLearned"),
]

words/urls.py
from django.urls import path
from .views import *




app_name = "words"

urlpatterns = [
    path('', panel,name="panel"),
    path('addWord/<int:pk>/', addWord,name="addWord"),
    path('addGroup/', addGroup,name="addGroup"),
    path('<int:pk>/', GpWords,name="home"),
    path('YourGp/', YourGp,name="YourGp"),
    # path('GpWords/<int:pk>/', GpWords,name="GpWords"),
    path('changeLearnCondition/<int:pk>', changeLearnCondition,name="changeLearnCondition"),

]

leitner/models.py
from django.db import models
from words.models import word
from django.utils import timezone
from datetime import timedelta
#-----------------------------------------------------------------
class Leitner(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.user.__str__() + " - " + self.title

    def search(self,text):
        for word in self.lword.all():
            if(str(text) == word.words.text):
                return True
        return False
#-----------------------------------------------------------------
class Lword(models.Model):
    status_word = (
        ('1','d1'),
        ('2','d2'),
        ('3','d3'),
        ('4','w1'),
        ('5','w2'),
        ('6','m1'),
        ('7','m2'),
    )
    words = models.ForeignKey(word, on_delete=models.CASCADE,related_name="Lword")
    cycle = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=1,choices = status_word,default='1')
    leitner = models.ForeignKey(Leitner, on_delete=models.CASCADE,related_name="lword")



    def learn(self):
        if self.cycle > timezone.now():
            return False
        else:
            return True

    def condition(self,days,delta):
        if( delta >= timedelta(days=days)):
            return True
        else:
            return False

    def reviewTime(self):
        delta = timezone.now() - self.cycle

        if self.status == '1':
            return self.condition(int(self.status),delta)

        elif self.status == '2':
            return self.condition(int(self.status),delta)

        elif self.status == '3':
            return self.condition(int(self.status),delta)

        elif self.status == '4':
            return self.condition(7,delta)

        elif self.status == '5':
            return self.condition(14,delta)

        elif self.status == '6':
            return self.condition(30,delta)

        elif self.status == '7':
            return self.condition(60,delta)



    def __str__(self):
        return self.words.text


    def UpLevel(self):
        self.status = str(int(self.status)+1)
        self.cycle = timezone.now()

    def DownLevel(self):
        self.status = str(1)
        self.cycle = timezone.now()

    def learned(self):
        self.cycle = timezone.now

    learn.boolean = True
    reviewTime.boolean = True


#-----------------------------------------------------------------

leitner/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
from words.models import *
import random

def test(request):
    l = Leitner.objects.get(id=1)
    lword = l.lword.get(id=2)
    # f = lword.status
    # lword.UpLevel()
    # lword.save()

    return HttpResponse(lword.cycle.day)


def addLword(request,id):
    w = word.objects.get(id=id)
    lw = Lword(words = w,status='1',leitner=request.user.leitner).save()

    return HttpResponse(lw)


#-----------------------------------------------------------------
def ReviewLeitner(request):
    lws = request.user.leitner.lword.all()

    w_id = [w.id for w in lws if w.reviewTime()]

    items = list(lws.filter(id__in=w_id))

    try:
        QueryWord = random.choice(items)
    except IndexError :
        QueryWord = None




    return render(request,'leitner/lw.html',{'QueryWord':QueryWord})
#-----------------------------------------------------------------
def WordLearned(request,id):
    lw = request.user.leitner.lword.get(id=id)
    lw.UpLevel()
    lw.save()

    return ReviewLeitner(request)
#-----------------------------------------------------------------
def WordUnLearned(request,id):
    lw = request.user.leitner.lword.get(id=id)
    lw.DownLevel()
    lw.save()

    return ReviewLeitner(request)

leitner/templates/leitner/lw.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism profile design</title>
  <link rel="stylesheet" href="{% static 'words/style2.css'%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="card">
  <div class="p-profile">
   <img src="{% static 'words/city.jpg' %}">
  </div>

  <div class="name">
    {% if QueryWord %}
    <h2>{{QueryWord.words}}</h2>

    <p>Level : {{QueryWord.status}}</p>
    <p id="anim"></p>


    {% else %}
    <h2>END!</h2>



    <!-- <p>perfect!</p> -->
    </br></br></br>
    {% endif %}
  </div>




  </br></br></br></br>
{% if QueryWord %}
<div class="button" style="margin-left: 70px;">
  <button id='btn'>Show meaning</button>
  </div>
  <div class="button">

    <button><a href="{% url 'leitner:WordUnLearned' QueryWord.id %}" style="text-decoration:none;Color:white">I dont know</a></button>
    <button><a href="{% url 'leitner:WordLearned' QueryWord.id %}" style="text-decoration:none;Color:blue">I Know</a></button>
    {% else %}
    <div class="button">
    <button style="margin-left: 65px;"><a href="{% url 'words:panel' %}" style="text-decoration:none;Color:white">Return Home</a></button>
    {% endif %}
  </div>

  <!-- <div class="infos">

     <div class="Follower">
      <h4>31</h4>
      <p>Post</p>
    </div>

    <div class="Follower">
      <h4>25k</h4>
      <p>Followers</p>
    </div>

    <div class="following">
      <h4>34</h4>
      <p>Following</p>
    </div>
  </div>

  <div class="more">
    <button>Visit Profile</button>
  </div> -->

</div>

<div class="circle1"></div>
<div class="circle2"></div>
<!-- partial -->



<script>
  var $ = function(id) {
  return document.getElementById(id);
};
var inc = 0;
var out = 0;
var str = "{{QueryWord.words.meaning}}";
var chars = 'ضصثقفغعهخحجچشسیبلاتنمکگظطزرذدپو';
var t;

var anim = function() {
  inc++;
  if (inc % 7 === 0 && out < str.length) {
    $('anim').appendChild(document.createTextNode(str[out]));
    out++;
  } else if (out >= str.length) {
    $('shuffle').innerHTML = '';
    removeInterval(t);
  }
  $('shuffle').innerHTML =
    chars[Math.floor(Math.random() * chars.length)];
};



function show() {
  t = setInterval(anim, 30);
  $('anim').innerHTML = '';

}

//Do it again
function reload() {
  window.location.href = window.location.href;
}
document.getElementById('btn').onclick = show;

</script>


</body>
</html>