core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words.urls')),
    path('', include('accounts.urls')),
    path('', include('leitner.urls')),
]


if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

words/urls.py
from django.urls import path
from .views import *




app_name = "words"

urlpatterns = [
    path('', panel,name="panel"),
    path('addWord/<int:pk>/', addWord,name="addWord"),
    path('addGroup/', addGroup,name="addGroup"),
    path('<int:pk>/', GpWords,name="home"),
    path('YourGp/', YourGp,name="YourGp"),
    # path('GpWords/<int:pk>/', GpWords,name="GpWords"),
    path('changeLearnCondition/<int:pk>', changeLearnCondition,name="changeLearnCondition"),

]

words/models.py
from django.db import models
from django.utils import timezone
from core.settings import AUTH_USER_MODEL as User

class group(models.Model):
    title = models.CharField(max_length=30)
    img = models.ImageField(null=True, blank=True)
    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name="groups")


    def __str__(self):
        return self.title

    def getId(self):
        return self.id


class word(models.Model):
    text = models.CharField(max_length=30)
    meaning = models.CharField(max_length=30)
    id = models.IntegerField(primary_key=True)
    gp = models.ForeignKey(group, on_delete=models.CASCADE,related_name="words")
    # cycle = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.text

    # def learn(self):
    #     if self.cycle > timezone.now():
    #         return False
    #     else:
    #         return True

    # def learned(self):
    #     self.cycle = timezone.now


    # learn.boolean = True

words/forms.py
from django import forms
from .models import *

class GpForm(forms.ModelForm):
    class Meta:
        model = group
        fields = ['title', 'img']


class WordForm(forms.ModelForm):
    class Meta:
        model = word
        fields = ['text', 'meaning']

words/views.py
from django.shortcuts import render
from .models import *
from leitner.models import *
import random
from .forms import *
from django.shortcuts import redirect



def home1(request):
    return render(request,'words/home.html')

#-----------------------------------------------------------------
def YourGp(request):
    gps = request.user.groups.all()
    print(gps)
    return render(request,'words/yourGp/YourGp.html',{'groups':gps})

#-----------------------------------------------------------------
def home(request,pk=0):
    max = word.objects.all().count()
    learned = word.objects.filter(learn=False).count()

    QueryWord = word.objects.get(id = 1)


    while((QueryWord.learn != False) and (learned!=1)):
        pk2 = random.randrange(1,max)
        QueryWord = word.objects.get(id = pk2)



    if(learned==1):
        QueryWord = word(text = "END!",meaning="cool!",id=1000)


    return render(request,'words/home.html',{'word':QueryWord})

#-----------------------------------------------------------------
def panel(request):
    groups = group.objects.all().order_by("-id")
    return render(request,'words/panel.html',{'groups':groups})
#-----------------------------------------------------------------
def addGroup(request):
    if request.method == 'POST':
        form = GpForm(request.POST, request.FILES)

        if form.is_valid():
            newgp = group(title = form.cleaned_data['title'],img = form.cleaned_data['img'],author=request.user).save()
            gp = group.objects.get(title=form.cleaned_data['title'])
            return redirect('words:addWord',gp.id)
    else:
        form = GpForm()
    return render(request,'words/addgp/name-pic.html',{'form':form})
#-----------------------------------------------------------------
def addWord(request,pk):
    if request.method == 'POST':
        form = WordForm(request.POST, request.FILES)

        if form.is_valid():
            newWord = word(text = form.cleaned_data['text'],meaning = form.cleaned_data['meaning'])
            gp = group.objects.get(id=pk)
            newWord.gp = gp
            newWord.save()
            return redirect('words:addWord',gp.id)
    else:
        form = WordForm()
    return render(request,'words/addgp/addWord.html',{'form':form})
#-----------------------------------------------------------------
def GpWords(request,pk):
    gp = group.objects.get(id = pk)
    wordsGP = gp.words.all()

    items = list(wordsGP)
    amount = 0

    for w in wordsGP:
        if(request.user.leitner.search(w)):
            pass
        else:
            amount+=1


    QueryWord = random.choice(items)

    while (request.user.leitner.search(QueryWord)) and (amount!=0):
        QueryWord = random.choice(items)



    if(amount==0):
        QueryWord = word(text = "END!",meaning="cool!",id=1000,gp=gp)

    return render(request,'words/group.html',{'word':QueryWord,'gp':gp})
#-----------------------------------------------------------------
def changeLearnCondition(request,pk):
    QueryWord = word.objects.get(id=pk)
    lt = request.user.leitner
    if not (lt.search(QueryWord)):
        lw = Lword(leitner=lt,words=QueryWord).save()
    lt.save()

    return GpWords(request,QueryWord.gp.id)
#-----------------------------------------------------------------

words/templates/words/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism-dashboard</title>
  <link rel="stylesheet" href="{% static 'words/panel/style2.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->

<div class="app">

 {% include 'words/base-elements/header.html' %}

 <div class="wrapper">
  <!-- {% include 'words/base-elements/warper.html' %} -->


  <div class="main-container">
   <!-- {% include 'words/base-elements/main-header.html' %} -->

   {% block content %}{% endblock %}
  </div>


 </div>

 <div class="overlay-app"></div>
</div>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script><script  src="{% static 'words/panel/script.js' %}"></script>

</body>
</html>

words/templates/words/group.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Glassmorphism profile design</title>
  <link rel="stylesheet" href="{% static 'words/style2.css'%}">

</head>
<body>
<!-- partial:index.partial.html -->
<div class="card">
  <div class="p-profile">
   <img src="{{gp.img.url}}">
  </div>

  <div class="name">
    <h2>{{word}}</h2>
    </br></br></br></br>
    <p>{{word.meaning}}</p>
  </div>




  </br></br></br></br>


  <div class="button">
    {% if word.text != "END!" %}
    <button><a href="{% url 'words:home' word.gp.id %}" style="text-decoration:none;Color:white">I dont know</a></button>
    <button><a href="{% url 'words:changeLearnCondition' word.id %}" style="text-decoration:none;Color:blue">I Know</a></button>
    {% else %}
    <button style="margin-left: 65px;"><a href="{% url 'words:panel' %}" style="text-decoration:none;Color:white">Return Home</a></button>
    {% endif %}
  </div>

  <!-- <div class="infos">

     <div class="Follower">
      <h4>31</h4>
      <p>Post</p>
    </div>

    <div class="Follower">
      <h4>25k</h4>
      <p>Followers</p>
    </div>

    <div class="following">
      <h4>34</h4>
      <p>Following</p>
    </div>
  </div>

  <div class="more">
    <button>Visit Profile</button>
  </div> -->

</div>

<div class="circle1"></div>
<div class="circle2"></div>
<!-- partial -->

</body>
</html>

words/templates/words/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Neumorphism Playlist</title>
  <link rel="stylesheet" href="{% static 'words/style.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="main">
  <div class="app">
    <h5 class="text">LEARN NOW</h5>

    <button class="btn arrow">
      <i class="fa fa-arrow-left"></i>
    </button>
    <button class="btn bar">
      <i class="fa fa-bars"></i>
    </button>

    <div class="image">
      <img src="{% static 'words/space.jpg' %}" style="width:200px">
      <h2>{{word}}</h2>
      </br></br>
      <p>{{word.meaning}}</p>
    </div>

  </br></br></br></br></br></br></br></br></br></br>




    <a href="{% url 'words:changeLearnCondition' word.id %}">
      <button class="btn period">
        <i class="fa fa-check"></i>
      </button>
    </a>

    <a href="{% url 'words:home' word.gp.id %}">
      <button class="btn perfect">
        <i class="fa fa-chevron-right"></i>
      </button>
    </a>



  </div>
</div>
<!-- partial -->

</body>
</html>

words/templates/words/panel.html
{% extends 'words/base.html' %}









{% block content %}
<div class="content-wrapper">


{% include 'words/panel-elements/cover.html' %}
{% include 'words/panel-elements/apps.html' %}
{% include 'words/panel-elements/installed.html' %}


</div>


{% endblock %}