accounts/urls.py
from django.urls import path
from . import views as viewsA


app_name= 'accounts'


urlpatterns = [
    path('profile/', viewsA.Profile.as_view() ,name='profile'),
    path('َUsers/PasswordChangeView',viewsA.PasswordChangeView.as_view(),name='PasswordChangeView'),
    path('login/',viewsA.Login,name="Login"),
    path('logout/',viewsA.logout,name="logout"),
    path('SignUp/',viewsA.SignUp,name="SignUp"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words.urls')),
    path('', include('accounts.urls')),
    path('', include('leitner.urls')),
]


if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

words/urls.py
from django.urls import path
from .views import *




app_name = "words"

urlpatterns = [
    path('', panel,name="panel"),
    path('addWord/<int:pk>/', addWord,name="addWord"),
    path('addGroup/', addGroup,name="addGroup"),
    path('<int:pk>/', GpWords,name="home"),
    path('YourGp/', YourGp,name="YourGp"),
    # path('GpWords/<int:pk>/', GpWords,name="GpWords"),
    path('changeLearnCondition/<int:pk>', changeLearnCondition,name="changeLearnCondition"),

]

words/models.py
from django.db import models
from django.utils import timezone
from core.settings import AUTH_USER_MODEL as User

class group(models.Model):
    title = models.CharField(max_length=30)
    img = models.ImageField(null=True, blank=True)
    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name="groups")


    def __str__(self):
        return self.title

    def getId(self):
        return self.id


class word(models.Model):
    text = models.CharField(max_length=30)
    meaning = models.CharField(max_length=30)
    id = models.IntegerField(primary_key=True)
    gp = models.ForeignKey(group, on_delete=models.CASCADE,related_name="words")
    # cycle = models.DateTimeField(default=timezone.now)


    def __str__(self):
        return self.text

    # def learn(self):
    #     if self.cycle > timezone.now():
    #         return False
    #     else:
    #         return True

    # def learned(self):
    #     self.cycle = timezone.now


    # learn.boolean = True

words/forms.py
from django import forms
from .models import *

class GpForm(forms.ModelForm):
    class Meta:
        model = group
        fields = ['title', 'img']


class WordForm(forms.ModelForm):
    class Meta:
        model = word
        fields = ['text', 'meaning']

words/views.py
from django.shortcuts import render
from .models import *
from leitner.models import *
import random
from .forms import *
from django.shortcuts import redirect



def home1(request):
    return render(request,'words/home.html')

#-----------------------------------------------------------------
def YourGp(request):
    gps = request.user.groups.all()
    print(gps)
    return render(request,'words/yourGp/YourGp.html',{'groups':gps})

#-----------------------------------------------------------------
def home(request,pk=0):
    max = word.objects.all().count()
    learned = word.objects.filter(learn=False).count()

    QueryWord = word.objects.get(id = 1)


    while((QueryWord.learn != False) and (learned!=1)):
        pk2 = random.randrange(1,max)
        QueryWord = word.objects.get(id = pk2)



    if(learned==1):
        QueryWord = word(text = "END!",meaning="cool!",id=1000)


    return render(request,'words/home.html',{'word':QueryWord})

#-----------------------------------------------------------------
def panel(request):
    groups = group.objects.all().order_by("-id")
    return render(request,'words/panel.html',{'groups':groups})
#-----------------------------------------------------------------
def addGroup(request):
    if request.method == 'POST':
        form = GpForm(request.POST, request.FILES)

        if form.is_valid():
            newgp = group(title = form.cleaned_data['title'],img = form.cleaned_data['img'],author=request.user).save()
            gp = group.objects.get(title=form.cleaned_data['title'])
            return redirect('words:addWord',gp.id)
    else:
        form = GpForm()
    return render(request,'words/addgp/name-pic.html',{'form':form})
#-----------------------------------------------------------------
def addWord(request,pk):
    if request.method == 'POST':
        form = WordForm(request.POST, request.FILES)

        if form.is_valid():
            newWord = word(text = form.cleaned_data['text'],meaning = form.cleaned_data['meaning'])
            gp = group.objects.get(id=pk)
            newWord.gp = gp
            newWord.save()
            return redirect('words:addWord',gp.id)
    else:
        form = WordForm()
    return render(request,'words/addgp/addWord.html',{'form':form})
#-----------------------------------------------------------------
def GpWords(request,pk):
    gp = group.objects.get(id = pk)
    wordsGP = gp.words.all()

    items = list(wordsGP)
    amount = 0

    for w in wordsGP:
        if(request.user.leitner.search(w)):
            pass
        else:
            amount+=1


    QueryWord = random.choice(items)

    while (request.user.leitner.search(QueryWord)) and (amount!=0):
        QueryWord = random.choice(items)



    if(amount==0):
        QueryWord = word(text = "END!",meaning="cool!",id=1000,gp=gp)

    return render(request,'words/group.html',{'word':QueryWord,'gp':gp})
#-----------------------------------------------------------------
def changeLearnCondition(request,pk):
    QueryWord = word.objects.get(id=pk)
    lt = request.user.leitner
    if not (lt.search(QueryWord)):
        lw = Lword(leitner=lt,words=QueryWord).save()
    lt.save()

    return GpWords(request,QueryWord.gp.id)
#-----------------------------------------------------------------

words/templates/words/base-elements/header.html
{% load static %}


<div class="header">
 <div class="menu-circle"></div>
 <div class="header-menu">
  <a class="menu-link is-active" href="{% url 'words:panel' %}">Home</a>
  {% if request.user.name %}
  <a class="menu-link " href="{% url 'accounts:logout' %}">logout</a>
  {% else %}
  <a class="menu-link " href="{% url 'accounts:Login' %}">login</a>
  {% endif %}
  <!-- <a class="menu-link notify" href="#">Your Groups</a>
  <a class="menu-link" href="{% url 'accounts:profile' %}">Profile</a> -->
  <!-- <a class="menu-link notify" href="#">Market</a> -->
 </div>
 <div class="search-bar">
  <input type="text" placeholder="Search">
 </div>
 <div class="header-profile">
   <div class="header-menu">
   <a class="menu-link" href="{% url 'accounts:profile' %}">{{request.user.name}}</a>
   </div>
   <img class="profile-img" src="{% static 'words/pro.jpg' %}" alt="">

  <!-- <div class="notification">
   <span class="notification-number">3</span>
   <svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell">
    <path d="M18 8A6 6 0 006 8c0 7-3 9-3 9h18s-3-2-3-9M13.73 21a2 2 0 01-3.46 0" />
   </svg>
  </div>
  <svg viewBox="0 0 512 512" fill="currentColor">
   <path d="M448.773 235.551A135.893 135.893 0 00451 211c0-74.443-60.557-135-135-135-47.52 0-91.567 25.313-115.766 65.537-32.666-10.59-66.182-6.049-93.794 12.979-27.612 19.013-44.092 49.116-45.425 82.031C24.716 253.788 0 290.497 0 331c0 7.031 1.703 13.887 3.006 20.537l.015.015C12.719 400.492 56.034 436 106 436h300c57.891 0 106-47.109 106-105 0-40.942-25.053-77.798-63.227-95.449z" />
  </svg> -->

 </div>
</div>

words/templates/words/base-elements/main-header.html
<div class="main-header">
 <a class="menu-link-main" href="#">All Apps</a>
 <div class="header-menu">
  <a class="main-header-link is-active" href="#">Desktop</a>
  <a class="main-header-link" href="#">Mobile</a>
  <a class="main-header-link" href="#">Web</a>

 </div>
</div>

words/templates/words/base-elements/warper.html
<div class="left-side">
 <div class="side-wrapper">
  <div class="side-title">Apps</div>
  <div class="side-menu">
   <a href="#">
    <svg viewBox="0 0 512 512">
     <g xmlns="http://www.w3.org/2000/svg" fill="currentColor">
      <path d="M0 0h128v128H0zm0 0M192 0h128v128H192zm0 0M384 0h128v128H384zm0 0M0 192h128v128H0zm0 0" data-original="#bfc9d1" />
     </g>
     <path xmlns="http://www.w3.org/2000/svg" d="M192 192h128v128H192zm0 0" fill="currentColor" data-original="#82b1ff" />
     <path xmlns="http://www.w3.org/2000/svg" d="M384 192h128v128H384zm0 0M0 384h128v128H0zm0 0M192 384h128v128H192zm0 0M384 384h128v128H384zm0 0" fill="currentColor" data-original="#bfc9d1" />
    </svg>
    Home
   </a>
   <a href="#">
    <svg viewBox="0 0 488.932 488.932" fill="currentColor">
     <path d="M243.158 61.361v-57.6c0-3.2 4-4.9 6.7-2.9l118.4 87c2 1.5 2 4.4 0 5.9l-118.4 87c-2.7 2-6.7.2-6.7-2.9v-57.5c-87.8 1.4-158.1 76-152.1 165.4 5.1 76.8 67.7 139.1 144.5 144 81.4 5.2 150.6-53 163-129.9 2.3-14.3 14.7-24.7 29.2-24.7 17.9 0 31.8 15.9 29 33.5-17.4 109.7-118.5 192-235.7 178.9-98-11-176.7-89.4-187.8-187.4-14.7-128.2 84.9-237.4 209.9-238.8z" />
    </svg>
    Updates
    <span class="notification-number updates">3</span>
   </a>
  </div>
 </div>



 <div class="side-wrapper">
  <div class="side-title">Settings</div>
  <div class="side-menu">
   <a href="#">
    <svg viewBox="0 0 488.455 488.455" fill="currentColor">
     <path d="M287.396 216.317c23.845 23.845 23.845 62.505 0 86.35s-62.505 23.845-86.35 0-23.845-62.505 0-86.35 62.505-23.845 86.35 0" />
     <path d="M427.397 91.581H385.21l-30.544-61.059H133.76l-30.515 61.089-42.127.075C27.533 91.746.193 119.115.164 152.715L0 396.86c0 33.675 27.384 61.074 61.059 61.074h366.338c33.675 0 61.059-27.384 61.059-61.059V152.639c-.001-33.674-27.385-61.058-61.059-61.058zM244.22 381.61c-67.335 0-122.118-54.783-122.118-122.118s54.783-122.118 122.118-122.118 122.118 54.783 122.118 122.118S311.555 381.61 244.22 381.61z" />
    </svg>
    Profile
   </a>
  </div>
 </div>

</div>